//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 01:39:03 AM EEST 
//


package com.epam.rd.java.basic.practice7.entity;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "book"
})
@XmlRootElement(name = "bookstore")
public class Bookstore {

    @XmlElement(required = true)
    private List<Book> books;

    public List<Book> getBooks() {
        if (books == null) {
            books = new ArrayList<>();
        }
        return books;
    }

    @Override
    public String toString() {
        if (books == null || books.isEmpty()) {
            return "Bookstore contains no books";
        }
        StringBuilder result = new StringBuilder();
        for (Book book : books) {
            result.append(book).append('\n');
        }
        return result.toString();
    }
}
