//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 01:39:03 AM EEST 
//


package com.epam.rd.java.basic.practice7.entity;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Book complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Book", propOrder = {
        "genre",
        "author",
        "title",
        "year",
        "series",
        "price"
})
public class Book {
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Genre genre;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String title;
    protected int year;
    protected String series;
    @XmlElement(required = true)
    protected Price price;
    @XmlAttribute(name = "id", namespace = "http://practice7.basic.java.rd.epam.com")
    protected Integer id;

    public Genre getGenre() {
        return genre;
    }

    public void setGenre(Genre value) {
        this.genre = value;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String value) {
        this.author = value;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int value) {
        this.year = value;
    }

    public String getSeries() {
        return series;
    }

    public void setSeries(String value) {
        this.series = value;
    }

    public Price getPrice() {
        return price;
    }

    public void setPrice(Price value) {
        this.price = value;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer value) {
        this.id = value;
    }

    @Override
    public String toString() {
        return "id    : " + id + "\n" +
                "genre : " + genre.value() + "\n" +
                "author: " + author + "\n" +
                "title : " + title + "\n" +
                "year  : " + year + "\n" +
                "series: " + series + "\n" +
                "price : " + price.value + " " + price.currency + "\n";
    }
}
