//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 01:39:03 AM EEST 
//


package com.epam.rd.java.basic.practice7.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Genre.
 */
@XmlType(name = "Genre")
@XmlEnum
public enum Genre {

    @XmlEnumValue("Fantasy")
    FANTASY("Fantasy"),
    @XmlEnumValue("Mystery")
    MYSTERY("Mystery"),
    @XmlEnumValue("Science Fiction")
    SCIENCE_FICTION("Science Fiction"),
    @XmlEnumValue("Urban Fiction")
    URBAN_FICTION("Urban Fiction"),
    @XmlEnumValue("Thriller")
    THRILLER("Thriller"),
    @XmlEnumValue("Historical")
    HISTORICAL("Historical"),
    @XmlEnumValue("Romance")
    ROMANCE("Romance");
    private final String value;

    Genre(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Genre fromValue(String v) {
        for (Genre c : Genre.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
