//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.26 at 01:39:03 AM EEST 
//


package com.epam.rd.java.basic.practice7.entity;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for Price complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Price", propOrder = {
        "value"
})
public class Price {
    @XmlValue
    protected BigDecimal value;
    @XmlAttribute(name = "currency", namespace = "http://practice7.basic.java.rd.epam.com")
    protected CurrencyType currency;

    public BigDecimal getValue() {
        return value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public CurrencyType getCurrency() {
        return currency;
    }

    public Price(BigDecimal value, CurrencyType currency) {
        this.value = value;
        this.currency = currency;
    }
}
